### ISSUE TITLE
Could not find 'matBlazor' in 'window' - Server Side Blazorboilerplate

### ISSUE THREAD

**Issue by veemat-home** [enkodellc/blazorboilerplate#179]
Microsoft.JSInterop.JSException: Could not find 'matBlazor' in 'window'.
Error: Could not find 'matBlazor' in 'window'.
    at http://localhost:53416/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (http://localhost:53416/_framework/blazor.server.js:8:30709)
    at http://localhost:53416/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:53416/_framework/blazor.server.js:8:31390)
    at http://localhost:53416/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:53416/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:53416/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)

**Comment by veemat-home** [comment]
The issue got resoved after downloading new source code
