### ISSUE TITLE
restructure branch tosses error on existing db

### ISSUE THREAD

**Issue by justSteve** [enkodellc/blazorboilerplate#196]
With my runtime problem solved and dotnet _--version_ now reporting _3.1.102_. I'm able to build and run. Now I'm getting an interesting set of errors that probably bears some investigation into differences of how the Seeding operation is handled between the 2 branches. Since **restructure** doesn't include any Migrations script the same database that worked for **master** should still work, right? 

I'm seeing the opposite -- my initial runs against **restructure** all toss a SQL exception with: _There is already an object named 'ApiResources' in the database._

If I change the connection string from `Initial Catalog=blazor_boilerplate;` to `Initial Catalog=blazor_boilerplate1;` (forces a re-scaffold of the db) a new db is created and the site pops up fully functional. Re-runs against that db work fine.

I've pasted my console's log that spells everything out but it boils down to this -- on my box, **restructure** tosses when it hits the original db. **master**'s branch works fine with that db but blows when it hits the db generated by _restructure_.

#starting point is against master branch with db connection hitting the one generated under .8
PM> update-database -Context ConfigurationDbContext
Build started...
Build succeeded.
Done.
PM> #Change db to original (against master)
PM> update-database -Context ConfigurationDbContext
Build started...
Build succeeded.
Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'ApiResources' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:ff61e4b9-2ed8-4adc-bb4d-c842ebe0d433
Error Number:2714,State:6,Class:16
There is already an object named 'ApiResources' in the database.
PM> #Change branch to restructure -- db is still the original 
& : File C:\Users\steve\.nuget\packages\microsoft.entityframeworkcore.tools\3.1.2\tools\init.ps1 cannot be loaded because running scripts is disabled on this system. For more 
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:45
+ ... rgs+=$_}; & 'C:\Users\steve\.nuget\packages\microsoft.entityframework ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PM> #test
PM> #Change branch to restructure -- db is still the original 
PM> update-database -Context ConfigurationDbContext
Build started...
Build succeeded.
Done.
PM> #and produced no error
PM> #
PM> #now switch db to the one generated by restructure v.8
PM> update-database -Context ConfigurationDbContext
Build started...
Build succeeded.
Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'ApiResources' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
ClientConnectionId:6812f429-b38b-4ca3-9ab7-e4b91a2af502
Error Number:2714,State:6,Class:16
There is already an object named 'ApiResources' in the database.
PM>

**Comment by enkodellc** [comment]
Try and delete your db and start from scratch?  I normally wipe the database and don't do much fur maintaining the migrations.

**Comment by justSteve** [comment]
Yeah -- that works and if you are satisfied it doesn't warrant further thought - enough said. If I were smarter than I am I'd be able to diff the schema between the 2 and confirm there's no differences (as I suspect) but it raises the question of why one db is triggering a re-scaffold and not the other. But then I'm reminded of your lack or love for EF ;).

How would Dapper handle a transition of the datamodel?

**Comment by soomon** [comment]
I'd guess your migrations in the second project do not  match the ones in the first project and thus inside of table "__EFMigrationsHistory". 
EF makes sure that your project's migrations match the applied migrations or apply whatever migrations are not yet applied to the database.

So if you create a project with migrations "migration1" and "migration2", apply them to the database, then try to access the database from another project that also has it's own creations, __EFMigrationsHistory will not match the 2nd project's migrations.
If I understand it correctly, it will then try to apply it's own migrations and it fails. Can you please check if "ApiResources" is the first table in your ConfigurationDbContextModelSnapshot?

I guess it's trying to apply it because it does not know it is already applied by a project using the same databaseInitializer.

I'm not sure if this is because of "a lack of live for EF" but more a security mechanism that makes sure your database is actually what it should be, although I do understand why you don't like it :)

**Comment by justSteve** [comment]
Sorry if i've been unclear -- I don't have any migrations nor to I think restructure has brought any. It appears that each branch thinks otherwise when it's running against the other branch's db. 

The curious thing (and what I _think would prove an interesting puzzle) is why, with no model changes -- no migrations to execute -- the regen is being attempted. It's not, as perhaps my earlier post referred - a seeding problem. The behavior is an attempt to run a CREATE statement against a db that already has the given table. 

Do you know the function of ConfigurationDbContextModelSnapshot? 

Initially, I'd thought 'Snapshot' meant it was kind of a checkpoint of schema at the point of the most recent migration. If I have time later in the week I might try to dig deeper.

Or it might just not matter. I have a habit of making rabbit holes out of thin air.

**Comment by DanielBunting** [comment]
I wouldn't be too surprised if there is no inter-compatibility between the two branches. There was essentially a lift and shift, completely changing/re-structuring the storage mechanism.

I believe the `ConfigurationDbContextModelSnapshot` is something similar to DacPac, which calculates the changes required between the current schema migration, and a more up to data schema. I read this article: https://www.learnentityframeworkcore.com/migrations/model-snapshot to gain some grounding.  

Being as the two databases are essentially differently constructed, it makes sense to me that the snapshots are incompatible.

**Comment by justSteve** [comment]
Thanks @DanielBunting -- I think that nails it and proves me wrong -- it _wasn't_ that interesting of a puzzle. ;) But at least it's a former puzzle.

**Comment by soomon** [comment]
> Sorry if i've been unclear -- I don't have any migrations nor to I think restructure has brought any. It appears that each branch thinks otherwise when it's running against the other branch's db.

BB always brings initial migrations built in. So each branch has their own migrations to create the DB when you launch it.

You download BB master and create the database from it. It knows which migrations have been applied and creates the history table.

Then you download BB restucture. It knows that is has never applied any migrations to the database. It's migrations have different names than the ones from master. Even should they have the same content, the date they have been created is different. As Packages may have been updates, they may also have different content. They have not been applied to the database. It tries to apply them and you get the error you mentioned.
