### ISSUE TITLE
Issue rendering new page

### ISSUE THREAD

**Issue by Brannos1970** [enkodellc/blazorboilerplate#319]
I am working with a copy of the boilerplate. I got everything up and running except the db log viewer.

I added a customer table to the database and set it up in the framework. I created a listing page similar to the ToDo listing. Other than the new web page and table I don't expect any issues with the page as it works exactly like to the ToDo listing.

When the page loads I get an error that I can't seem to debug. From that point on I can't get the web application to do anything unless I navigate away and then refresh the page. As long as I don't try to visit the customer listing page everything works as expected.

During debugging I thought I saw an issue with the chat client. In the Serilog file I get the following error:

2020-05-14 14:44:32.062 -05:00 [ERR] Unhandled exception in circuit 'akuvRFjDPvGJq_-ep40uWQ1mHBAMaVhhDR69NVQwxBg'.
Microsoft.JSInterop.JSException: e.addEventListener is not a function
TypeError: e.addEventListener is not a function
    at new c (http://localhost:53414/_content/MatBlazor/dist/matBlazor.js:1:340523)
    at Object.e.init (http://localhost:53414/_content/MatBlazor/dist/matBlazor.js:1:338884)
    at http://localhost:53414/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:53414/_framework/blazor.server.js:8:31390)
    at http://localhost:53414/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:53414/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:53414/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://localhost:53414/_framework/blazor.server.js:1:10276)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
   at MatBlazor.BaseMatTooltip.<.ctor>b__28_0()
   at MatBlazor.BaseMatComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

Any ideas on how I can track down the issue?

**Comment by enkodellc** [comment]
Without seeing your code it is not something I can easily debug. I guess I would start with either removing the MatBlazor / MatTable part of your UI to see if it is something done... so the page will load and make sure you do not get errors and the data is returned correctly. That will isolate the front / backend a bit.

**Comment by Brannos1970** [comment]
I finally found the issue, it is the MatToolTip component. I will have to look into that later to see if I can figure it out. Thanks for the help.

**Comment by GioviQ** [comment]
I think it is related to
https://github.com/SamProf/MatBlazor/issues/469
https://github.com/SamProf/MatBlazor/issues/303

**Comment by enkodellc** [comment]
@Brannos1970 glad you found it. Are you using forms? I am a collaborator on MatBlazor so if you want you can take it a step further and download the "develop" repo and create a test to see if it is something you can fix. We are slowly getting through all the issues  and PR's in MatBlazor. It takes a lot of time and we are not getting paid so it is not a priority for most of us.

I had some issues with MatToolTip as well so I just removed it for now from parts of Blazor Boilerplate.

I am going to close this issue here as it is not related to BB.
