### ISSUE TITLE
System.Text.Json Decimal Type

### ISSUE THREAD

**Issue by mhartwig123** [enkodellc/blazorboilerplate#320]
I am getting the below when using a decimal in my Model:

`2020-05-14 11:24:29.822 -07:00 [WRN] Unhandled exception rendering component: The JSON value could not be converted to BlazorBoilerplate.Shared.Dto.ApiResponseDto. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
System.Text.Json.JsonException: The JSON value could not be converted to BlazorBoilerplate.Shared.Dto.ApiResponseDto. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at BlazorBoilerplate.CommonUI.Pages.OfferList.ReadOffers() in C:\Users\MikeHartwig\Desktop\blazorboilerplate-master\src\BlazorBoilerplate.CommonUI\Pages\OfferList.razor:line 185
   at BlazorBoilerplate.CommonUI.Pages.OfferList.OnInitializedAsync() in C:\Users\MikeHartwig\Desktop\blazorboilerplate-master\src\BlazorBoilerplate.CommonUI\Pages\OfferList.razor:line 180
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
2020-05-14 11:24:29.899 -07:00 [ERR] Unhandled exception in circuit 'KG_OkRlRRMjOPVOSt5Nn3zL95lvbPLIQEyQCWWWaECU'.`

`[Column(TypeName = "Money")]
        public decimal OfferBillingAmount { get; set; }`

I have looked through the code and cant find where System.Text.Json is being used. It is commented out everywhere I can find. 

From what I can tell from google, System.Text.Json has a problem with Decimal data types.

**Comment by enkodellc** [comment]
Thanks for using BlazorBoilerplate and the info. What are your expectations from posting an issue here? 

I am not sure if I ran into that before but I know there were reasons to use Newtonsoft instead of System.Text.Json

**Comment by mhartwig123** [comment]
I had to change my model from a decimal to a double to make this work. I guess this is a bug in system.text.json, which is a dependancy of system.net.http.json and Microsoft.AspNetCore.HttpClient. Just FYI in case anybody comes across this when trying to use a decimal in your model because system.text.json cannot deserialize decimals apparently.
