### ISSUE TITLE
Unable to locate metadata resource for: http://localhost:53414/api/data/ {Development}

### ISSUE THREAD

**Issue by trihugger** [enkodellc/blazorboilerplate#409]
I've encountered this error recently on a test site I've been working on of BPP.

I tried to replicate and created a clean version cloned from the development branch as of yesterday to stage the error.

The error happens when I login to the site after creating a new datamodel in Breeze.

Here's the full error:
```
blazor.server.js:19 [2020-09-20T15:19:23.687Z] Error: System.Exception: Unable to locate metadata resource for: http://localhost:53414/api/data/
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Breeze.Sharp.MetadataStore.UpdateStructuralTypeFromJNode(JNode jNode, Boolean isFromServer)
   at Breeze.Sharp.MetadataStore.<>c__DisplayClass53_0.<DeserializeFrom>b__2(JNode jn)
   at Breeze.Sharp.Core.EnumerableFns.ForEach[T](IEnumerable`1 items, Action`1 action)
   at Breeze.Sharp.MetadataStore.DeserializeFrom(JNode jNode, Boolean isFromServer)
   at Breeze.Sharp.MetadataStore.ImportMetadata(JNode jNode, Boolean isFromServer)
   at Breeze.Sharp.MetadataStore.ImportMetadata(String metadata, Boolean isFromServer)
   at Breeze.Sharp.MetadataStore.FetchMetadata(DataService dataService, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Breeze.Sharp.MetadataStore.FetchMetadata(DataService dataService, CancellationToken cancellationToken)
   at Breeze.Sharp.EntityManager.FetchMetadata(CancellationToken cancellationToken, DataService dataService)
   at Breeze.Sharp.EntityManager.FetchMetadata(DataService dataService)
   at Breeze.Sharp.EntityManager.ExecuteQuery(EntityQuery query, CancellationToken cancellationToken)
   at Breeze.Sharp.EntityManager.ExecuteQuery[T](EntityQuery`1 query, CancellationToken cancellationToken)
   at BlazorBoilerplate.Shared.Services.ApiClient.GetUserProfile() in C:\*\repos\TestBreezeComplex\src\Shared\BlazorBoilerplate.Shared\Services\ApiClient.cs:line 21
   at BlazorBoilerplate.Shared.Services.AppState.GetUserProfile() in C:\*\repos\TestBreezeComplex\src\Shared\BlazorBoilerplate.Shared\Services\AppState.cs:line 62
   at BlazorBoilerplate.Theme.Material.Shared.Layouts.MainLayout.OnInitializedAsync() in C:\*\repos\TestBreezeComplex\src\Shared\Modules\BlazorBoilerplate.Theme.Material\Shared\Layouts\MainLayout.razor:line 70
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Here's the changes:

DataModel: Test.cs
```
using BlazorBoilerplate.Infrastructure.Storage.DataInterfaces;
using BlazorBoilerplate.Shared.Dto.Db;
using Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace BlazorBoilerplate.Infrastructure.Storage.DataModels
{
    public partial class Test : IAuditable, ISoftDelete
    {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }

        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }

        public Statuses RecordStatus { get; set; }
    }
}
```

DTO: Test.Cs
```
using BlazorBoilerplate.Shared.Dto.Db;
using Breeze.Sharp;
using System;
using System.Collections.Generic;
using System.Text;

namespace BlazorBoilerplate.Shared.Dto
{
    public partial class Test : BaseEntity
    {
        public Int64 Id
        {
            get { return GetValue<Int64>(); }
            set { SetValue(value); }
        }

        public String Name
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String Address1
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String Address2
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String City
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String State
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public String Zip
        {
            get { return GetValue<String>(); }
            set { SetValue(value); }
        }

        public Statuses RecordStatus
        {
            get { return GetValue<Statuses>(); }
            set { SetValue(value); }
        }

        //Add the following for the purpose of IAuditable and ISoftDelete functionality
        public Guid? CreatedById
        {
            get { return GetValue<Guid?>(); }
            set { SetValue(value); }
        }

        public DateTime CreatedOn
        {
            get { return GetValue<DateTime>(); }
            set { SetValue(value); }
        }

        public Boolean IsDeleted
        {
            get { return GetValue<Boolean>(); }
            set { SetValue(value); }
        }

        public Guid? ModifiedById
        {
            get { return GetValue<Guid?>(); }
            set { SetValue(value); }
        }

        public DateTime ModifiedOn
        {
            get { return GetValue<DateTime>(); }
            set { SetValue(value); }
        }
        public ApplicationUser CreatedBy
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }

        public ApplicationUser ModifiedBy
        {
            get { return GetValue<ApplicationUser>(); }
            set { SetValue(value); }
        }
    }
}
```

GlobalEnums.cs.
```
using System;
using System.Collections.Generic;
using System.Text;

namespace BlazorBoilerplate.Shared.Dto.Db
{
    public enum Statuses
    {
        Pending,
        Complete,
        Reviewed
    }
}
```

ApplicationDbContext.cs:
`        public DbSet<Test> Tests { get; set; }`

ApplicationController.cs:
```
        [HttpGet]
        public IQueryable<Test> Tests()
        {
            return persistenceManager.GetEntities<Test>().Include(i => i.CreatedBy).Include(i => i.ModifiedBy).OrderBy(i => i.Id);
        }
```

ApiClient.cs (and its reference in IApiClient.cs):
```
        public async Task<QueryResult<Test>> GetTests()
        {
            return await GetItems<Test>(from: "Tests", orderByDescending: i => i.CreatedOn);
        }
```

Thank you for all your help,

Jeff

**Comment by GioviQ** [comment]
In the database the IAuditable and ISoftDelete fields of Test table are present?

**Comment by trihugger** [comment]
They are, here's the script generated from the SQL Object Explorer.

```
USE [BlazorBoilerplate]
GO

/****** Object: Table [dbo].[Tests] Script Date: 9/20/2020 1:05:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tests] (
    [Id]           BIGINT           IDENTITY (1, 1) NOT NULL,
    [Name]         NVARCHAR (MAX)   NULL,
    [Address1]     NVARCHAR (MAX)   NULL,
    [Address2]     NVARCHAR (MAX)   NULL,
    [City]         NVARCHAR (MAX)   NULL,
    [State]        NVARCHAR (MAX)   NULL,
    [Zip]          NVARCHAR (MAX)   NULL,
    [CreatedOn]    DATETIME2 (7)    NOT NULL,
    [ModifiedOn]   DATETIME2 (7)    NOT NULL,
    [CreatedById]  UNIQUEIDENTIFIER NULL,
    [ModifiedById] UNIQUEIDENTIFIER NULL,
    [IsDeleted]    BIT              NOT NULL,
    [RecordStatus] INT              NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_Tests_CreatedById]
    ON [dbo].[Tests]([CreatedById] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_Tests_ModifiedById]
    ON [dbo].[Tests]([ModifiedById] ASC);


GO
ALTER TABLE [dbo].[Tests]
    ADD CONSTRAINT [PK_Tests] PRIMARY KEY CLUSTERED ([Id] ASC);


GO
ALTER TABLE [dbo].[Tests]
    ADD CONSTRAINT [FK_Tests_AspNetUsers_CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
ALTER TABLE [dbo].[Tests]
    ADD CONSTRAINT [FK_Tests_AspNetUsers_ModifiedById] FOREIGN KEY ([ModifiedById]) REFERENCES [dbo].[AspNetUsers] ([Id]);
```

**Comment by GioviQ** [comment]
If you only added Test entity, remove  Test entity and watch if the error disappears. So you can exclude other origins.

**Comment by trihugger** [comment]
If I remove all the files list above and the entries in ApplicationDbContext, ApiClient, and ApplicationController. The site works without a problem and no errors exist at login.

**Comment by GioviQ** [comment]
Found the issue: wrong namespace for dto Test.

Try with BlazorBoilerplate.Shared.Dto.Db.

**Comment by GioviQ** [comment]
In https://github.com/enkodellc/blazorboilerplate/blob/development/src/Shared/BlazorBoilerplate.Shared/Services/BaseApiClient.cs

you see the current namespace mapping.

**Comment by trihugger** [comment]
That's it, OMG can't believe I missed it. Thank you :D

**Comment by enkodellc** [comment]
Nice work @GioviQ
