### ISSUE TITLE
Blazor problem with publish in iis.

### ISSUE THREAD

**Issue by charlie0992** [enkodellc/blazorboilerplate#58]
It works correctly when running from the exe. but when it comes to the iis, it tends to present the problem with the error, so all pages are waiting to authorize and the answers are loading ..

![error](https://user-images.githubusercontent.com/13168127/68532770-f2f38280-02e6-11ea-8438-adab623b98a1.JPG)

**Comment by enkodellc** [comment]
Just from the look of your error it might look like a appsettings.json issue... There are some instructions on the readme for deploying to IIS.  That is how I deploy https://blazorboilerplate.com the demo. Please review your appsettings.json, web.config and the instructions. If you need more help then I will try but of course it is not a simple thing when it is on your server..

**Comment by enkodellc** [comment]
Any update on this??

**Comment by enkodellc** [comment]
I am closing since I have not heard a response. Can re-open if there is specific issue related to Blazor Boilerplate

**Comment by charlie0992** [comment]
Sorry for not responding on time, the problem was resolved,
apparently it was tempkey.rsa.

**Comment by charlie0992** [comment]
> I am closing since I have not heard a response. Can re-open if there is specific issue related to Blazor Boilerplate


Sorry for not responding on time, the problem was resolved,
apparently it was tempkey.rsa

**Comment by enkodellc** [comment]
Thanks for following up so is there anything I can put in my instructions for IIS Deployment or adjust in the repo to help others? Anything to help others if they run into this issue.

**Comment by charlie0992** [comment]
> Thanks for following up. Is there anything I can put in my instructions for IIS Deployment or adjust in the repo to help others?

Sure, The steps are: 
1.[ IIS configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0#iis-configuration) 
2.[ Install Runtime & Hosting Bundle ASP.NET Core/.NET Core](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.1.0-preview2-windows-hosting-bundle-installer)
3.  [Install URL Rewrite Module](https://www.iis.net/downloads/microsoft/url-rewrite#additionalDownloads)
4. [Create Site](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0#create-the-iis-site)
5. Create publish in folder profile (Server only).
6. Publish (Server project)
7. Copy files in folder site IIS.

**Comment by mobinseven** [comment]
> Sure, The steps are:
> 1.[ IIS configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0#iis-configuration)
> 2.[ Install Runtime & Hosting Bundle ASP.NET Core/.NET Core](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.1.0-preview2-windows-hosting-bundle-installer)
> 3. [Install URL Rewrite Module](https://www.iis.net/downloads/microsoft/url-rewrite#additionalDownloads)
> 4. [Create Site](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-3.0#create-the-iis-site)
> 5. Create publish in folder profile (Server only).
> 6. Publish (Server project)
> 7. Copy files in folder site IIS.
After doing these steps I got this in server logs:
`[FTL] BlazorBoilerplate Host terminated unexpectedly
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at BlazorBoilerplate.Server.Startup.ConfigureServices(IServiceCollection services) in C:\Users\MobinPc\Downloads\blazorboilerplate-master\blazorboilerplate-master\src\BlazorBoilerplate.Server\Startup.cs:line 141
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
...`

**Comment by mobinseven** [comment]
> * First do you have your SSL Installed in the WebHosting certificate store?

I don't have one. Is there any way to ditch SSL?

**Comment by enkodellc** [comment]
@mobinseven - Well of course it is not recommended to pass user credentials across a website without SSL.  I have not done it but you will have to update your urls and try out a few other items like this:

https://stackoverflow.com/questions/47019923/how-to-disabling-ssl-for-identityserver4

I am not sure if that is your only things you need to do but that is where I would start.

**Comment by mobinseven** [comment]
> * First do you have your SSL Installed in the WebHosting certificate store?
> * Did you put your SSL thumbprint in the appsettings.production.config?
> * Did you set "UseLocalCertStore: "true" in the appsettings.production.config?

I used a self-signed SSL and did as you said. Still getting the same error. Any ideas?

**Comment by mobinseven** [comment]
> * First do you have your SSL Installed in the WebHosting certificate store?
> * Did you put your SSL thumbprint in the appsettings.production.config?
> * Did you set "UseLocalCertStore: "true" in the appsettings.production.config?

I used a [self-signed SSL certificate](https://babelway.zendesk.com/hc/en-us/community/posts/360027367853-HOW-TO-CREATE-SELF-SIGNED-SSL-CERTIFICATES-IN-WINDOWS-10) and the problem got solved. Thanks to you.

**Comment by enkodellc** [comment]
@mobinseven, Glad you got the issue solved. Is there anything in my instructions in my readme that you would recommend I would change.

**Comment by mobinseven** [comment]
> Is there anything in my instructions in my repo's readme for IIS that you would recommend I would change?
 
Yes:

1. I tested this on my Windows 10 laptop without SQL server installed. Just VS2019. (I think this is the most minimalist setup). So you may want to make it more general (not mentioning special version, etc.)
2. Steps 1 to 3 should be changed to one step: 
Publish Server project to your IIS website folder. 
(If you're making changes to project, in one click your changes will be on the stage)
