### ISSUE TITLE
Unable to locate metadata resource for: https://testdomain.org:port/api/data/

### ISSUE THREAD

**Issue by maddadder** [enkodellc/blazorboilerplate#706]
I cannot seem to track this error down. If you happened to have seen this before and know what the cause please let me know. The home page loads fine, but anything I click on that depends on the api seems to fail.

[2021-10-18T12:36:08.501Z] Error: System.Exception: Unable to locate metadata resource for: https://testdomain.org:[port]/api/data/
 ---> System.Net.Http.HttpRequestException: Name or service not known (testdomain.org:[port])
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Breeze.Sharp.DataService.GetAsync(String resourcePath, CancellationToken cancellationToken)
   at Breeze.Sharp.MetadataStore.FetchMetadata(DataService dataService, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Breeze.Sharp.MetadataStore.FetchMetadata(DataService dataService, CancellationToken cancellationToken)
   at Breeze.Sharp.EntityManager.FetchMetadata(CancellationToken cancellationToken, DataService dataService)
   at Breeze.Sharp.EntityManager.FetchMetadata(DataService dataService)
   at Breeze.Sharp.EntityManager.ExecuteQuery(EntityQuery query, CancellationToken cancellationToken)
   at Breeze.Sharp.EntityManager.ExecuteQuery[T](EntityQuery`1 query, CancellationToken cancellationToken)
   at BlazorBoilerplate.Shared.Services.BaseApiClient.GetItems[T](String from, Expression`1 predicate, Expression`1 orderBy, Expression`1 orderByDescending, Nullable`1 take, Nullable`1 skip, Dictionary`2 parameters) in /src/Shared/BlazorBoilerplate.Shared/Services/BaseApiClient.cs:line 173
   at BlazorBoilerplate.Shared.Services.ApiClient.GetTodoCreators(ToDoFilter filter) in /src/Shared/BlazorBoilerplate.Shared/Services/ApiClient.cs:line 55
   at BlazorBoilerplate.Theme.Material.Demo.Pages.TodoList.LoadFilters(String propertyName) in /src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/Pages/TodoList.razor:line 180
   at BlazorBoilerplate.Theme.Material.Demo.Pages.TodoList.OnInitializedAsync() in /src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo/Pages/TodoList.razor:line 151
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by maddadder** [comment]
I am now and now it works in docker. Now I'm trying to get it running in microk8s kubernetes. I updated the error message (it's different now)
