### ISSUE TITLE
Could not load file or assembly 'MatBlazor, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by EmergentCybernetics** [enkodellc/blazorboilerplate#748]
Testing a build of the current `master` branch today and getting this error when the server starts up:

```
2021-12-06 15:21:50 [FTL] BlazorBoilerplate Host terminated unexpectedly
System.IO.FileNotFoundException: Could not load file or assembly 'MatBlazor, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MatBlazor, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null'
   at BlazorBoilerplate.Theme.Material.Module.ConfigureServices(IServiceCollection services)
   at BlazorBoilerplate.Server.Extensions.ModuleLoader.AddModules(IServiceCollection services) in C:\Users\MyUser\Documents\blazorboilerplate\src\Server\BlazorBoilerplate.Server\Extensions\ModuleLoader.cs:line 41
   at BlazorBoilerplate.Server.Startup.ConfigureServices(IServiceCollection services) in C:\Users\MyUser\Documents\blazorboilerplate\src\Server\BlazorBoilerplate.Server\Startup.cs:line 662
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at BlazorBoilerplate.Server.Program.Main(String[] args) in C:\Users\MyUser\Documents\blazorboilerplate\src\Server\BlazorBoilerplate.Server\Program.cs:line 34

```

Seems to be a namespace conflict between the new `BlazorBoilerplate.Theme.MudBlazor` and the old `BlazorBoilerplate.Theme.Material`. Maybe this is the issue?
https://github.com/enkodellc/blazorboilerplate/blob/911551b508eb784547049a82ad5f03cc4eae427e/src/Shared/Modules/BlazorBoilerplate.Theme.MudBlazor/Module.cs#L12

**Comment by maddadder** [comment]
I had this same problem. I was able to fix by cloning the repo into a new folder and building from there. I work in vscode so I can't do a clean. You could try a clean.

**Comment by EmergentCybernetics** [comment]
@maddadder Thanks. I've tried a `Build > Clean Solution` from VisualStudio and `dotnet clean`, but it's not working. I'll try a new directory.

btw, thanks for this https://github.com/enkodellc/blazorboilerplate/pull/747
Was about to dig into that today as well. Had noticed issues with these on linux:
https://github.com/enkodellc/blazorboilerplate/blob/911551b508eb784547049a82ad5f03cc4eae427e/src/Shared/BlazorBoilerplate.Shared/EntityGeneratorConfig.json#L2

https://github.com/enkodellc/blazorboilerplate/blob/911551b508eb784547049a82ad5f03cc4eae427e/src/Shared/BlazorBoilerplate.Shared.DataInterfaces/EntityGeneratorConfig.json#L2

Switching to `/` fixed that, but I'll be trying your PR for linux if I can get past this `Could not load file or assembly 'MatBlazor` issue.

**Comment by EmergentCybernetics** [comment]
@maddadder new directory seems to have worked on both Window and linux.

Did a diff and the offending files seems to be in `src\Server\BlazorBoilerplate.Server\Modules`:
![blazorboilerp](https://user-images.githubusercontent.com/42426103/144938029-0a360a94-a48b-4639-b072-3bbf5473275f.png)

**Comment by EmergentCybernetics** [comment]
Can also remove these from `src\Server\BlazorBoilerplate.Server\Themes\MatBlazor`
![blazorboilerp](https://user-images.githubusercontent.com/42426103/144938357-80db8d0d-b234-4b21-a6e4-805f0bb9be83.png)
:
