### ISSUE TITLE
SQL provider has an issue with 'cold start'

### ISSUE THREAD

**Issue by MarkStega** [enkodellc/blazorboilerplate#97]
I forked & cloned blazorboilerplate. During startup with no settings changed I take an exception in the server startup.cs on line 304 (databaseintializzer.seed...) of 
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Error occurred during LocalDB instance startup: SQL Server process failed to start.
))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BlazorBoilerplate.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Solutions\OHI\blazorboilerplate\src\BlazorBoilerplate.Server\Startup.cs:line 304
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

Inner Exception 1:
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Error occurred during LocalDB instance startup: SQL Server process failed to start.
)

Inner Exception 2:
Win32Exception: Unknown error (0x89c5010a)
```
Simply changing to SqlLite resolves the issue. Not having used SQL in local mode are there any suggestions?

**Comment by enkodellc** [comment]
@MarkStega, glad you tried SQL Lite. 

- Are you confident your connection string is correct and works? It seems like LocalDB is not a valid DB server for you.

- Did you check your error logs in the "Logs" folder in the server project? 

- I use:     "DefaultConnection": "Data Source=localhost;Initial Catalog=blazor_boilerplate;Trusted_Connection=True;MultipleActiveResultSets=true",

- https://github.com/enkodellc/blazorboilerplate#problem-solving-tips

- This also might help: https://stackoverflow.com/questions/13287252/cannot-start-localdb

**Comment by MarkStega** [comment]
I have SQL 2017 with the LocalDB option installed; Not certain what the issue is; In any case I can switch the connection string to point to the instance of SQL server (localhost//SQLExpress) and everything is happy (as it was with SQL Lite). From the command line I can issue 'sqllocaldb info' and get back two instances (MSSQLLocalDB and ProjectsV13). However when I try to start mssqllocaldb it fails. It's not worth my time to try to figure this out. In any case this isn't an issue with Blazor Boilerplate.
